# LogLevel debug

ServerName uafs_frontend

<VirtualHost *:80>
    DocumentRoot /usr/local/apache2/htdocs

    ProxyPreserveHost On

    ProxyPass           "/Admin/"       "http://uafs_backend:5000/Admin/"
    ProxyPassReverse    "/Admin/"       "http://uafs_backend:5000/Admin/"

    ProxyPass           "/Advisor/"     "http://uafs_backend:5000/Advisor/"
    ProxyPassReverse    "/Advisor/"     "http://uafs_backend:5000/Advisor/"

    ProxyPass           "/Student/"     "http://uafs_backend:5000/Student/"
    ProxyPassReverse    "/Student/"     "http://uafs_backend:5000/Student/"

    ProxyPass           "/Schedule/"     "http://uafs_backend:5000/Schedule/"
    ProxyPassReverse    "/Schedule/"     "http://uafs_backend:5000/Schedule/"

    ProxyPass           "/DegreePlan/"     "http://uafs_backend:5000/DegreePlan/"
    ProxyPassReverse    "/DegreePlan/"     "http://uafs_backend:5000/DegreePlan/"

    <Directory /usr/local/apache2/htdocs>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"
        Header set Access-Control-Allow-Headers "Authorization, Content-Type"
        Header set Access-Control-Expose-Headers "Authorization"
    </Directory>
</VirtualHost>