# Development (Vite) 
# FROM node:20-alpine AS dev

# WORKDIR /app
# COPY Frontend/package*.json .
# RUN npm install
# COPY Frontend/ .
# RUN rm -rf node_modules package-lock.json \
#     && npm install

# EXPOSE 5173
# CMD ["npm", "run", "dev", "--", "--host"]

# Production (Apache) 
FROM node:20-alpine AS builder
WORKDIR /app

COPY Frontend/package*.json .
RUN npm install
COPY Frontend/ .
# RUN rm -rf node_modules package-lock.json \
#     && npm install \
#     && npm run build
RUN npm run build

FROM httpd:2.4-alpine AS prod

COPY --from=builder app/dist/ /usr/local/apache2/htdocs/
COPY Frontend/.htaccess /usr/local/apache2/htdocs/



COPY Frontend/apache.conf /usr/local/apache2/conf/extra/apache-vhost.conf
RUN echo "LoadModule proxy_module modules/mod_proxy.so" >> /usr/local/apache2/conf/httpd.conf \
 && echo "LoadModule headers_module modules/mod_headers.so" >> /usr/local/apache2/conf/httpd.conf \
 && echo "LoadModule proxy_http_module modules/mod_proxy_http.so" >> /usr/local/apache2/conf/httpd.conf \
 && echo "Include conf/extra/apache-vhost.conf" >> /usr/local/apache2/conf/httpd.conf 
RUN echo "LoadModule rewrite_module modules/mod_rewrite.so" >> /usr/local/apache2/conf/httpd.conf

EXPOSE 8080

CMD ["httpd-foreground"]