# Development (Vite) 
FROM node:20-alpine AS dev
WORKDIR /app
COPY Frontend/package.json .
COPY Frontend/ .
RUN rm -rf node_modules package-lock.json \
    && npm install
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]

FROM node:20-alpine AS builder
WORKDIR /app
COPY Frontend/package.json .
COPY Frontend/ .
RUN rm -rf node_modules package-lock.json \
    && npm install \
    && npm run build

# Production (Apache) 
FROM httpd:2.4-alpine
COPY --from=builder /app/dist/ /usr/local/apache2/htdocs/